### ISSUE TITLE
Add functional-style transactions to hidalgo stores

### ISSUE THREAD

**Issue by fungl164** [hidal-go/hidalgo#10]
Is there any interest in extending the DB Store interface to include functional-style transaction-based views for reading and updating values using well-known interfaces?

E.g.:
```golang
type Store interface {
	...
	// Tx opens a read-only or read-write transaction in the tuple store.
	Tx(rw bool) (Tx, error)
	// View provides functional-style read-only transaction in the tuple store.
	View(func(tx Tx) error) error
	// Update provides functional-style read-write transaction in the tuple store.
	Update(func(tx Tx) error) error
}
```

**Comment by dennwc** [comment]
Not really. Have you seen the `View` and `Update` helpers in `kv` package?

**Comment by fungl164** [comment]
I was thinking something generic as in https://github.com/fungl164/hidalgo/tree/feature/transactional-views might be useful.  Thnxs for all the hard work!

**Comment by dennwc** [comment]
It's a bit too much copy-paste for all stores, tbh :(

I was thinking that it might be useful to have something like this:

```go
package kv

type Store interface {
   // ...
   Tx(rw bool) (Tx, error)
}

type DB struct{
   Store
}

func (db DB) View(f func(tx Tx) error) error {
 // ...
}
```

So basically having a wrapper type that extends Store and implements all the convenience functions.

**Comment by dennwc** [comment]
Merged, will figure out how to reduce boilerplate when it will become too much.
